-- =============================================================================
-- Migration 005 — Gift Cards + Stores (Phase 5)
-- =============================================================================
--   * gift_cards — issued gift card codes with running balance
--   * stores     — physical stores for the locator page (designed to grow
--                  past the one Greenhills location)
--
-- Gift card delivery: when a customer buys a gift card via /gift-cards.html,
-- a row is inserted with status='pending' and the unique code. The admin
-- (or future automated webhook) can mark it 'active' once payment clears.
-- Redemption flow is applied at checkout via the gift card code.
--
-- Run AFTER migration 004.
-- =============================================================================


-- =============================================================================
-- GIFT CARDS
-- =============================================================================

create table gift_cards (
  id              uuid primary key default gen_random_uuid(),

  -- Customer-shareable code (e.g. "DU-A4F2-9X7B"). Generated by the
  -- /gift-cards.html purchase page and emailed/handed to the recipient.
  code            text not null unique,

  -- Face value at issue time in PHP. Never changes.
  amount          numeric(10, 2) not null check (amount > 0),

  -- Remaining balance. Decremented at checkout when the card is redeemed.
  -- When this hits 0 the card is "spent" but the row stays for auditability.
  balance         numeric(10, 2) not null check (balance >= 0),

  -- Optional recipient details captured during purchase
  recipient_email text,
  recipient_name  text,
  sender_name     text,
  message         text,

  -- 'pending' — purchased but not yet paid/issued
  -- 'active'  — paid and usable
  -- 'spent'   — balance reached 0
  -- 'cancelled' — voided by an admin
  status          text not null default 'pending'
                    check (status in ('pending', 'active', 'spent', 'cancelled')),

  -- Optional link back to the order that bought this card
  purchased_in_order_id uuid references orders (id) on delete set null,

  -- Customer email of the buyer (used to surface the card in their account)
  purchaser_email text,

  expires_at      timestamptz,   -- null = never expires
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index gift_cards_status_idx on gift_cards (status);
create index gift_cards_purchaser_email_idx on gift_cards (purchaser_email);

comment on table gift_cards is
  'Issued gift card codes with running balance. Redemption decrements balance at checkout.';


-- =============================================================================
-- STORES
-- =============================================================================

create table stores (
  id          uuid primary key default gen_random_uuid(),

  -- Display name shown on the locator
  name        text not null,

  -- Full address rendered on the store card
  address     text not null,
  city        text not null,
  province    text,
  postal_code text,

  phone       text,
  email       text,

  -- Weekly hours stored as a JSON object keyed by day:
  --   { "Mon": "10:00–20:00", "Tue": "10:00–20:00", ... "Sun": "closed" }
  hours       jsonb,

  -- Coordinates for the embedded map (Google Maps iframe uses lat/lng).
  lat         numeric(9, 6),
  lng         numeric(9, 6),

  -- Optional descriptive blurb shown beneath the store card
  description text,

  -- Optional hero photo
  image_url   text,

  -- When false, the store is hidden from /stores.html (e.g. temporarily closed)
  is_active   boolean not null default true,

  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index stores_is_active_idx on stores (is_active, display_order);

comment on table stores is
  'Physical store locations shown on /stores.html. is_active toggles visibility.';


-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

alter table gift_cards enable row level security;
alter table stores     enable row level security;


-- ── gift_cards ──────────────────────────────────────────────────────────────
-- Codes are sensitive (anyone with the code can redeem). So:
--   * Public CANNOT read gift_cards directly. Validation goes through an
--     admin-callable function or a future redeem RPC.
--   * Anyone can INSERT (purchase a card from the storefront), but only as
--     a 'pending' row — admins promote to 'active' after payment confirms.
--   * Customers can read their own purchased cards (matched by purchaser_email).
--   * Admins can read + update all.

create policy "Anyone can purchase a gift card"
  on gift_cards for insert
  with check (status = 'pending');

create policy "Customers can read their own purchased cards"
  on gift_cards for select
  using (purchaser_email = auth.jwt() ->> 'email');

create policy "Admins can read all gift cards"
  on gift_cards for select using (public.is_admin());

create policy "Admins can update gift cards"
  on gift_cards for update using (public.is_admin());

create policy "Admins can delete gift cards"
  on gift_cards for delete using (public.is_admin());


-- ── stores ──────────────────────────────────────────────────────────────────

create policy "Public can read active stores"
  on stores for select using (is_active = true);

create policy "Admins can read all stores"
  on stores for select using (public.is_admin());

create policy "Admins can insert stores"
  on stores for insert with check (public.is_admin());

create policy "Admins can update stores"
  on stores for update using (public.is_admin());

create policy "Admins can delete stores"
  on stores for delete using (public.is_admin());


-- =============================================================================
-- SEED — the Greenhills flagship
-- =============================================================================

insert into stores (name, address, city, province, postal_code, phone, hours, lat, lng, description, display_order)
values (
  'Greenhills Flagship',
  'Ducks Unlimited Workshop, Greenhills Shopping Center',
  'San Juan',
  'Metro Manila',
  '1500',
  '+63 9XX XXX XXXX',
  jsonb_build_object(
    'Mon', '10:00 – 20:00',
    'Tue', '10:00 – 20:00',
    'Wed', '10:00 – 20:00',
    'Thu', '10:00 – 20:00',
    'Fri', '10:00 – 21:00',
    'Sat', '10:00 – 21:00',
    'Sun', '11:00 – 19:00'
  ),
  14.6047, 121.0411,
  'Our original family workshop and showroom. Stop by to see the cloth woven, the hems hand-finished, and the full collection in person.',
  0
)
on conflict do nothing;
